In [15]:
import numpy as np

import tensorflow as tf

import skimage
from skimage import data, color
from skimage.transform import rescale, resize, downscale_local_mean

import cv2

import matplotlib.pyplot as plt

In [16]:
tf.__version__, skimage.__version__, cv2.__version__

('2.4.1', '0.18.1', '4.5.2')

In [17]:
H, W = 3, 3
RESIZED_H, RESIZED_W = 2 * H, 2 * W

In [18]:
# Create Input H x W x 1 image
#IMG = np.random.rand(1, H, W, 1)
IMG = np.arange(1.0, 1.0 + H * W).reshape(H, W)
IMG

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [19]:
# tf.compat.v1.image.resize_bilinear
#
# align_corners=False
TF = tf.compat.v1.image.resize_bilinear(
    IMG.reshape(1, H, W, 1),
    (RESIZED_H, RESIZED_W), 
    align_corners=False,
).numpy().reshape(RESIZED_H, RESIZED_W)

print(TF.shape)

TF

(6, 6)


array([[1. , 1.5, 2. , 2.5, 3. , 3. ],
       [2.5, 3. , 3.5, 4. , 4.5, 4.5],
       [4. , 4.5, 5. , 5.5, 6. , 6. ],
       [5.5, 6. , 6.5, 7. , 7.5, 7.5],
       [7. , 7.5, 8. , 8.5, 9. , 9. ],
       [7. , 7.5, 8. , 8.5, 9. , 9. ]], dtype=float32)

In [20]:
# tf.compat.v1.image.resize_bilinear
#
# align_corners=True
TF = tf.compat.v1.image.resize_bilinear(
    IMG.reshape(1, H, W, 1),
    (RESIZED_H, RESIZED_W), 
    align_corners=True,
).numpy().reshape(RESIZED_H, RESIZED_W)

print(TF.shape)

TF

(6, 6)


array([[1.       , 1.4      , 1.8      , 2.2      , 2.6      , 3.       ],
       [2.2      , 2.6      , 3.       , 3.4      , 3.8      , 4.2      ],
       [3.4      , 3.8000002, 4.2000003, 4.6      , 5.       , 5.4      ],
       [4.6000004, 5.       , 5.4000006, 5.8      , 6.2000003, 6.6000004],
       [5.8      , 6.2000003, 6.6000004, 7.       , 7.4      , 7.8      ],
       [7.       , 7.4      , 7.8      , 8.2      , 8.6      , 9.       ]],
      dtype=float32)

In [21]:
# Open CV
CV2 = cv2.resize(IMG.reshape(H, W), dsize=(RESIZED_H, RESIZED_W), interpolation=cv2.INTER_LINEAR)

print(CV2.shape)

CV2

(6, 6)


array([[1.  , 1.25, 1.75, 2.25, 2.75, 3.  ],
       [1.75, 2.  , 2.5 , 3.  , 3.5 , 3.75],
       [3.25, 3.5 , 4.  , 4.5 , 5.  , 5.25],
       [4.75, 5.  , 5.5 , 6.  , 6.5 , 6.75],
       [6.25, 6.5 , 7.  , 7.5 , 8.  , 8.25],
       [7.  , 7.25, 7.75, 8.25, 8.75, 9.  ]])

In [22]:
# Scikit Image
# https://scikit-image.org/docs/dev/auto_examples/transform/plot_rescale.html
# https://scikit-image.org/docs/dev/api/skimage.transform.html#skimage.transform.resize
SKI = resize(IMG, (RESIZED_H, RESIZED_W), order=1)

print(SKI.shape)

SKI

(6, 6)


array([[2. , 2. , 2.5, 3. , 3.5, 3.5],
       [2. , 2. , 2.5, 3. , 3.5, 3.5],
       [3.5, 3.5, 4. , 4.5, 5. , 5. ],
       [5. , 5. , 5.5, 6. , 6.5, 6.5],
       [6.5, 6.5, 7. , 7.5, 8. , 8. ],
       [6.5, 6.5, 7. , 7.5, 8. , 8. ]])