In [2]:
import numpy as np
import tensorflow as tf

In [15]:
H = 1
W = 3
W_RATIO = 2

X = np.arange(1, H * W + 1).reshape(H, W)
X

array([[1, 2, 3]])

In [16]:
Y = tf.compat.v1.image.resize_bilinear(
  X.reshape(1, H, W, 1),
  (1 * H, W_RATIO * W),
  align_corners=True,
)

Y.numpy().reshape(W_RATIO * W)

array([1. , 1.4, 1.8, 2.2, 2.6, 3. ], dtype=float32)

In [20]:
X_OFF = 2.0 / 5.0 * np.arange(0, 6)

X_OFF

array([0. , 0.4, 0.8, 1.2, 1.6, 2. ])

In [34]:
OFFSET = 1.6

FLOOR_OFFSET = int(np.floor(OFFSET))
CEIL_OFFSET = int(np.ceil(OFFSET))

FLOOR_VALUE = X.reshape(-1)[FLOOR_OFFSET]
CEIL_VALUE = X.reshape(-1)[CEIL_OFFSET]

VALUE = FLOOR_VALUE * (1 - (OFFSET - FLOOR_OFFSET)) + CEIL_VALUE * (1 - (CEIL_OFFSET - OFFSET))
VALUE

# 1.0 * (1 - 0.4) + 2.0 * (1 - 0.6)

2.6