In [5]:
import numpy as np

import tensorflow as tf

import skimage
from skimage import data, color
from skimage.transform import rescale, resize, downscale_local_mean

import cv2

import matplotlib.pyplot as plt

In [6]:
tf.__version__, skimage.__version__, cv2.__version__

('2.4.1', '0.18.1', '4.5.2')

In [7]:
H, W = 2, 2
RESIZED_H, RESIZED_W = 4, 4

In [8]:
# Create Input H x W x 1 image
#IMG = np.random.rand(1, H, W, 1)
IMG = np.array([[1.0, 2.0], [3.0, 4.0]])

In [9]:
# TensorFlow Data
TF = [None, None]

# align_corners=False
TF[0] = tf.compat.v1.image.resize_bilinear(
    IMG.reshape(1, H, W, 1),
    (RESIZED_H, RESIZED_W), 
    align_corners=False,
).numpy().reshape(RESIZED_H, RESIZED_W)

# align_corners=True
TF[1] = tf.compat.v1.image.resize_bilinear(
    IMG.reshape(1, H, W, 1),
    (RESIZED_H, RESIZED_W), 
    align_corners=True,
).numpy().reshape(RESIZED_H, RESIZED_W)

# Scikit Image
# https://scikit-image.org/docs/dev/auto_examples/transform/plot_rescale.html
SKI = resize(IMG, (RESIZED_H, RESIZED_W))

# Open CV
CV2 = cv2.resize(IMG.reshape(H, W), dsize=(RESIZED_H, RESIZED_W), interpolation=cv2.INTER_LINEAR)

In [10]:
TF[0]

array([[1. , 1.5, 2. , 2. ],
       [2. , 2.5, 3. , 3. ],
       [3. , 3.5, 4. , 4. ],
       [3. , 3.5, 4. , 4. ]], dtype=float32)

In [11]:
TF[1]

array([[1.       , 1.3333334, 1.6666667, 2.       ],
       [1.6666667, 2.       , 2.3333335, 2.6666667],
       [2.3333335, 2.6666665, 3.       , 3.3333335],
       [3.       , 3.3333333, 3.6666667, 4.       ]], dtype=float32)

In [12]:
CV2

array([[1.  , 1.25, 1.75, 2.  ],
       [1.5 , 1.75, 2.25, 2.5 ],
       [2.5 , 2.75, 3.25, 3.5 ],
       [3.  , 3.25, 3.75, 4.  ]])

In [13]:
SKI

array([[1.75, 1.75, 2.25, 2.25],
       [1.75, 1.75, 2.25, 2.25],
       [2.75, 2.75, 3.25, 3.25],
       [2.75, 2.75, 3.25, 3.25]])